tasks:
  - init: |
      sudo apt-get update -y
      sudo apt-get install -y git build-essential gdb-multiarch qemu-system-misc gcc-riscv64-linux-gnu binutils-riscv64-linux-gnu

vscode:
  extensions:
    - ms-vscode.cpptools-extension-pack
    - mhutchie.git-graph
